export const extracteur_elixir_noir1 = {
    extracteur_elixir_noir1_nv_0: { capacite: 0, prh: 0, pv: 0, prix: 0, tconstru: 0, exp_gagner: 0, hdvrequis: 7, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir0.png" },
    extracteur_elixir_noir1_nv_1: { capacite: 160, prh: 20, pv: 800, prix: 180000, tconstru: "4h", exp_gagner: 120, hdvrequis: 7, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir1.png" },
    extracteur_elixir_noir1_nv_2: { capacite: 300, prh: 30, pv: 860, prix: 270000, tconstru: "6h", exp_gagner: 146, hdvrequis: 7, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir2.png" },
    extracteur_elixir_noir1_nv_3: { capacite: 540, prh: 45, pv: 920, prix: 540000, tconstru: "12h", exp_gagner: 207, hdvrequis: 7, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir3.png" },
    extracteur_elixir_noir1_nv_4: { capacite: 840, prh: 60, pv: 980, prix: 900000, tconstru: "18h", exp_gagner: 254, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir4.png" },
    extracteur_elixir_noir1_nv_5: { capacite: 1280, prh: 80, pv: 1060, prix: 1200000, tconstru: "1d", exp_gagner: 293, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir5.png" },
    extracteur_elixir_noir1_nv_6: { capacite: 1800, prh: 100, pv: 1160, prix: 1800000, tconstru: "1d 12h", exp_gagner: 360, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir6.png" },
    extracteur_elixir_noir1_nv_7: { capacite: 2400, prh: 120, pv: 1280, prix: 2100000, tconstru: "1d 18h", exp_gagner: 388, hdvrequis: 10, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir7.png" },
    extracteur_elixir_noir1_nv_8: { capacite: 3000, prh: 140, pv: 1380, prix: 2400000, tconstru: "2d", exp_gagner: 415, hdvrequis: 11, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir8.png" },
    extracteur_elixir_noir1_nv_9: { capacite: 3600, prh: 160, pv: 1480, prix: 3700000, tconstru: "3d", exp_gagner: 509, hdvrequis: 12, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir9.png" },
    extracteur_elixir_noir1_nv_10: { capacite: 4200, prh: 180, pv: 1550, prix: 5300000, tconstru: "4d", exp_gagner: 587, hdvrequis: 14, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir10.png" },
};

export const extracteur_elixir_noir2 = {
    extracteur_elixir_noir2_nv_0: { capacite: 0, prh: 0, pv: 0, prix: 0, tconstru: 0, exp_gagner: 0, hdvrequis: 8, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir0.png" },
    extracteur_elixir_noir2_nv_1: { capacite: 160, prh: 20, pv: 800, prix: 180000, tconstru: "4h", exp_gagner: 120, hdvrequis: 8, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir1.png" },
    extracteur_elixir_noir2_nv_2: { capacite: 300, prh: 30, pv: 860, prix: 270000, tconstru: "6h", exp_gagner: 146, hdvrequis: 8, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir2.png" },
    extracteur_elixir_noir2_nv_3: { capacite: 540, prh: 45, pv: 920, prix: 540000, tconstru: "12h", exp_gagner: 207, hdvrequis: 8, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir3.png" },
    extracteur_elixir_noir2_nv_4: { capacite: 840, prh: 60, pv: 980, prix: 900000, tconstru: "18h", exp_gagner: 254, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir4.png" },
    extracteur_elixir_noir2_nv_5: { capacite: 1280, prh: 80, pv: 1060, prix: 1200000, tconstru: "1d", exp_gagner: 293, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir5.png" },
    extracteur_elixir_noir2_nv_6: { capacite: 1800, prh: 100, pv: 1160, prix: 1800000, tconstru: "1d 12h", exp_gagner: 360, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir6.png" },
    extracteur_elixir_noir2_nv_7: { capacite: 2400, prh: 120, pv: 1280, prix: 2100000, tconstru: "1d 18h", exp_gagner: 388, hdvrequis: 10, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir7.png" },
    extracteur_elixir_noir2_nv_8: { capacite: 3000, prh: 140, pv: 1380, prix: 2400000, tconstru: "2d", exp_gagner: 415, hdvrequis: 11, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir8.png" },
    extracteur_elixir_noir2_nv_9: { capacite: 3600, prh: 160, pv: 1480, prix: 3700000, tconstru: "3d", exp_gagner: 509, hdvrequis: 12, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir9.png" },
    extracteur_elixir_noir2_nv_10: { capacite: 4200, prh: 180, pv: 1550, prix: 5300000, tconstru: "4d", exp_gagner: 587, hdvrequis: 14, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir10.png" },
};

export const extracteur_elixir_noir3 = {
    extracteur_elixir_noir3_nv_0: { capacite: 0, prh: 0, pv: 0, prix: 0, tconstru: 0, exp_gagner: 0, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir0.png" },
    extracteur_elixir_noir3_nv_1: { capacite: 160, prh: 20, pv: 800, prix: 180000, tconstru: "4h", exp_gagner: 120, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir1.png" },
    extracteur_elixir_noir3_nv_2: { capacite: 300, prh: 30, pv: 860, prix: 270000, tconstru: "6h", exp_gagner: 146, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir2.png" },
    extracteur_elixir_noir3_nv_3: { capacite: 540, prh: 45, pv: 920, prix: 540000, tconstru: "12h", exp_gagner: 207, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir3.png" },
    extracteur_elixir_noir3_nv_4: { capacite: 840, prh: 60, pv: 980, prix: 900000, tconstru: "18h", exp_gagner: 254, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir4.png" },
    extracteur_elixir_noir3_nv_5: { capacite: 1280, prh: 80, pv: 1060, prix: 1200000, tconstru: "1d", exp_gagner: 293, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir5.png" },
    extracteur_elixir_noir3_nv_6: { capacite: 1800, prh: 100, pv: 1160, prix: 1800000, tconstru: "1d 12h", exp_gagner: 360, hdvrequis: 9, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir6.png" },
    extracteur_elixir_noir3_nv_7: { capacite: 2400, prh: 120, pv: 1280, prix: 2100000, tconstru: "1d 18h", exp_gagner: 388, hdvrequis: 10, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir7.png" },
    extracteur_elixir_noir3_nv_8: { capacite: 3000, prh: 140, pv: 1380, prix: 2400000, tconstru: "2d", exp_gagner: 415, hdvrequis: 11, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir8.png" },
    extracteur_elixir_noir3_nv_9: { capacite: 3600, prh: 160, pv: 1480, prix: 3700000, tconstru: "3d", exp_gagner: 509, hdvrequis: 12, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir9.png" },
    extracteur_elixir_noir3_nv_10: { capacite: 4200, prh: 180, pv: 1550, prix: 5300000, tconstru: "4d", exp_gagner: 587, hdvrequis: 14, image: "/coc/image/village principal/batiment/ressource/extracteur elixir noir/extracteur elixir noir10.png" },
};